---

- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `username` variable needs to be provided to this playbook, via --extra-vars"
  when: "username is not defined or username == '<username>'"

- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `email` variable needs to be provided to this playbook, via --extra-vars"
  when: "email is not defined or email == '<email>'"

- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `password` variable needs to be provided to this playbook, via --extra-vars"
  when: "password is not defined or password == '<password>'"

- ansible.builtin.set_fact:
    initial_role: user
  tags:
  - gotosocial-add-user

- ansible.builtin.set_fact:
    initial_role: admin
  tags:
  - gotosocial-add-admin

- ansible.builtin.set_fact:
    user:
      username: "{{ username }}"
      initial_email: "{{ email }}"
      initial_password: "{{ password }}"
      initial_type: "{{ initial_role }}"


- name: Ensure GoToSocial is started
  ansible.builtin.service:
    name: "{{ gotosocial_identifier }}"
    state: started
    daemon_reload: true
  register: start_result

- name: Wait a while, so that the GoToSocial instance can manage to start
  ansible.builtin.pause:
    seconds: 7
  when: "start_result.changed"

- name: Ensure GoToSocial user is created
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/util/ensure_user_registered.yml"
  no_log: true
