---
- name: Ensure GoToSocial is started
  ansible.builtin.service:
    name: "{{ gotosocial_identifier }}"
    state: started
    daemon_reload: true
  register: start_result

- name: Wait a while, so that the GoToSocial instance can manage to start
  ansible.builtin.pause:
    seconds: 7
  when: "start_result.changed"

- name: Ensure GoToSocial users are created
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/util/ensure_user_registered.yml"
  with_items: "{{ gotosocial_users }}"
  loop_control:
    loop_var: user
  no_log: true
